function generateEmailTemplate(username, email, message) {
  return `
<div
  style="
    font-family: 'Segoe UI', Arial, sans-serif;
    max-width: 800px;
    margin: 30px auto;
    background: #ffffff;
    border-radius: 14px;
    overflow: hidden;
    border: 1px solid #e1e1e1;
    box-shadow: 0 8px 20px rgba(0, 0, 0, 0.1);
  "
>
  <!-- Header -->
  <div
    style="
      background: linear-gradient(135deg, #b71c1c, #d32f2f, #c62828);
      padding: 35px 30px;
      text-align: center;
      color: #ffffff;
    "
  >
    <h1 style="margin: 0; font-size: 30px; font-weight: 700">
      📬 Livana Contact Submission
    </h1>
    <p style="margin-top: 10px; font-size: 17px; opacity: 0.95">
      A visitor has contacted your support team through your website.
    </p>
  </div>

  <!-- Intro Section -->
  <div style="padding: 30px">
    <p style="font-size: 17px; color: #444; line-height: 1.7">
      Hello Team Livana,<br /><br />
      You have received a new message from the <strong>Contact Us</strong> page.
      Please find the details below.
    </p>
  </div>

  <!-- Divider -->
  <div style="height: 1px; background: #f0b3b3; margin: 0 30px"></div>

  <!-- User Info Section -->
  <div style="padding: 30px">
    <h2 style="color: #c62828; font-size: 22px; margin-bottom: 15px">
      👤 Sender Information
    </h2>

    <div
      style="
        background: #fff4f4;
        padding: 20px;
        border-radius: 12px;
        border: 1px solid #f1bcbc;
        box-shadow: 0 2px 6px rgba(0, 0, 0, 0.05);
      "
    >
      <p style="font-size: 17px; margin: 6px 0">
        <strong style="color: #c62828">Full Name:</strong> ${username}
      </p>
      <p style="font-size: 17px; margin: 6px 0">
        <strong style="color: #c62828">Email Address:</strong> ${email}
      </p>
      <p style="font-size: 17px; margin: 6px 0">
        <strong style="color: #c62828">Message Submitted On:</strong> ${new Date().toLocaleString()}
      </p>
    </div>
  </div>

  <!-- Divider -->
  <div style="height: 1px; background: #f0b3b3; margin: 0 30px"></div>

  <!-- Message Section -->
  <div style="padding: 30px">
    <h2 style="color: #c62828; font-size: 22px; margin-bottom: 15px">
      📝 Message Content
    </h2>

    <div
      style="
        padding: 25px;
        background: #ffffff;
        border-radius: 12px;
        border-left: 6px solid #c62828;
        border: 1px solid #f1bcbc;
        box-shadow: 0 3px 8px rgba(0, 0, 0, 0.04);
        line-height: 1.8;
      "
    >
      <p style="font-size: 17px; color: #444; white-space: pre-wrap">
        ${message}
      </p>
    </div>
  </div>

  <!-- Divider -->
  <div style="height: 1px; background: #f0b3b3; margin: 0 30px"></div>

  <!-- Footer -->
  <div
    style="
      padding: 25px 30px;
      background: #fafafa;
      text-align: center;
      border-top: 1px solid #e5e5e5;
    "
  >
    <p style="margin: 0; font-size: 15px; color: #777">
      This is an automated message generated by your website.
    </p>
    <p style="margin-top: 8px; font-size: 14px; color: #999">
      © ${new Date().getFullYear()} Your Company. All Rights Reserved.
    </p>
  </div>
</div>
`;
}

module.exports = generateEmailTemplate;
